name: Update ECS

on: workflow_dispatch

jobs:
  pull-latest-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get-latest-tag.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get latest tag
        id: get-latest-tag
        run: |
          echo "tag=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV
          echo "::set-output name=tag::$(git describe --tags `git rev-list --tags --max-count=1`)"