name: 'Reusable workflow'

description: 'A composite action that accepts two inputs and prints them as environment variables'

inputs:
  var1:
    description: 'Environment variable 1'
    required: true
    default: '123'
  var2:
    description: 'Environment variable 2'
    required: true
    default: '456'

outputs:
  output_var1:
    description: 'Output variable 1'
  output_var2:
    description: 'Output variable 2'

runs:
  using: "composite"
  steps:
    - name: Set up environment variables
      run: |
        echo "ENV_VAR1=${{ inputs.var1 }}" >> $GITHUB_ENV
        echo "output_var1=${{ inputs.var1 }}" >> $GITHUB_OUTPUT
    - name: Check environment variables
      run: |
        echo "ENV_VAR2=${{ inputs.var2 }}" >> $GITHUB_ENV
        echo "output_var2=${{ inputs.var2 }}" >> $GITHUB_OUTPUT
    - name: Print environment variables
      run: |
        echo "ENV_VAR1: $ENV_VAR1"
        echo "ENV_VAR2: $ENV_VAR2"