name: 'Main Workflow'

on:
  push:
    branches:
      - env_test

jobs:
  call-env-test-1:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Call env_test with first set of values
        uses: ./.github/workflows/env_test
        with:
          var1: 'abc'
          var2: 'xyz'
      - name: Call env_test with second set of values
        uses: ./.github/workflows/env_test
        with:
          var1: '111'
          var2: '222'