name: 'Steps Test Workflow'

on:
  push:
    branches:
      - env_test

jobs:
  steps-test:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Echo message
        id: step1
        shell: bash
        run: | 
            echo "This is step 1"

            echo "ecr_image_tag=0.1.0" >> $GITHUB_ENV

      - name: Step 2 - Designed to test
        id: step2
        if: success()
        shell: bash
        run: |
            echo "This is step 2"
            echo ${{ env.ecr_image_tag }}
            echo "ecr_image_tag=0.1.1" >> $GITHUB_ENV
      - name: Step 3 - Print conclusion
        if: success()
        shell: bash
        run: |
            echo "Conclusion: Steps 1 and 2 have been executed."
            echo "Step 1: ${{ steps.step1.conclusion }}"
            echo "Step 2: ${{ steps.step2.conclusion }}"
            echo "${{ steps.step1.conclusion == 'success' && steps.step2.conclusion == 'failure' }}"
            echo ${{ env.ecr_image_tag }}
            cat $GITHUB_ENV
    
