name: Update ECS
Description: Update ECS service with new task definition
on:
  push:
    branches:
      - feature/ga-branch-test

jobs:
  update-ecs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update ECS
        uses: ./.github/workflows/update-ecs
        with:
          workspace_id: "wf-aavnsvdfjed"
          image_tag: "v1.0.0"
      - name: Print outputs
        run: |
          echo "Previous image tag: ${{ env.previous_image_tag }}"
          echo "Current image tag: ${{ env.current_image_tag }}"