name: Update ECS

on: workflow_dispatch

jobs:
  pull-latest-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest tag
        id: get-latest-tag
        run: |
          echo "tag=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_OUTPUT

      - name: Print latest tag
        run: |
          echo "Latest tag: ${{ steps.get-latest-tag.outputs.tag }}"