name: Update ECS

on:
  push:
    branches:
      - feature/ga-branch-test

jobs:
  update-ecs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update ECS
        id: update-ecs
        uses: ./.github/workflows/update-ecs
        with:
          workspace_id: "wf-aavnsvdfjed"
          image_tag: "v1.0.0"
      - name: Print outputs
        shell: bash   
        run: |
            echo "Current image tag: ${{ steps.update-ecs.outputs.current_image_tag }}"

      - name: fail-step
        run: exit 1
        shell: bash
      - name: revert-step
        run: echo "Reverting the image tag changes"
        shell: bash
        if: failure()
        uses: ./.github/workflows/update-ecs
        with:
          workspace_id: "wf-aavnsvdfjed"
          image_tag: "v1.0.1"